spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/es-java?createDatabaseIfNotExist=true

mybatis:
  # default value
  #    annotationClass: org.springframework.boot.mybatis.autoconfigure.Mapper
  #    configLocation: "mybatis-configuration.xml"
  mapper-locations: "classpath:com.thanhnd101.mapper.sql/*.xml"
  type-aliases-package: "com.thanhnd101.enrich.core.entity"

  # If the 'spring.mybatis.configLocation' property is used when the 'spring.mybatis.configurationProperties' property is ignored.
  configuration-properties:
    aggressiveLazyLoading: false
    lazyLoadingEnabled: true
    lazyLoadTriggerMethods: ""
    mapUnderscoreToCamelCase: true
logging:
  level:
    root: DEBUG